# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::249050106719:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-G9ZUA8YH6K7D
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::249050106719:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-31T19:59:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "826"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4839a9cf-334c-4407-89e1-821ae22037eb
